[[constraint]]
  name = "gopkg.in/resty.v1"
  version = "1.9.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.*"
